# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace # trims trailing whitespace
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending # replaces or checks mixed line ending
    -   id: check-symlinks # checks for symlinks which do not point to anything
    -   id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
    # Git
    -   id: check-merge-conflict # checks for files that contain merge conflict strings
    # Python
    -   id: check-docstring-first # checks a common error of defining a docstring after code
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        name: black for fits-finder
        args: ["--config=./fits-finder/pyproject.toml", "./fits-finder"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.6'
    hooks:
    -   id: ruff
        name: ruff for fits-finder
        args: ["--config=./fits-finder/pyproject.toml", "--fix", "./fits-finder"]
