host = "0.0.0.0:80"
ip_headers = ["x-real-ip", "x-forwarded-for"]
ip_headers_recursive = true
log_level = "info"
response_headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET" }
threads = 2

[healthcheck]
interval = 5
timeout = 3

[geoip]
type = "ripe-geo"
autoupdate = true

[mirrors.sai]
upstream = "https://sai.fits.ztf.snad.space/"
healthcheck = "https://sai.fits.ztf.snad.space/products/"

[mirrors.uci]
upstream = "https://uci.fits.ztf.snad.space/"
healthcheck = "https://uci.fits.ztf.snad.space/products/"

[continents]
Africa = ["sai", "uci"]
Asia = ["sai", "uci"]
Europe = ["sai", "uci"]
NorthAmerica = ["uci", "sai"]
Oceania = ["uci", "sai"]
SouthAmerica = ["uci", "sai"]
Antarctica = ["uci", "sai"]
default = ["sai", "uci"]
